export {default as img1} from './geneology.jpg'
export {default as img2} from './blog-1.jpg'
export {default as img3} from './project-2.png'
export {default as img4} from './project-3.png'
export {default as logo} from './suber_logo1.png'
