export {default as LoginScreen} from './Auth/login/LoginScreen'
export {default as RegisterScreen} from './Auth/register/RegisterScreen'
export {default as ForgotPasswordScreen} from './Auth/forgotPassword/ForgotPasswordScreen'
export {default as ResetPasswordScreen} from './Auth/resetPassword/ResetPasswordScreen'
export {default as IndexPage} from './privatePages/indexPage/IndexPage'
