export {default as LoginScreen2} from './Auth/login/LoginScreen2'
export {default as RegisterScreen} from './Auth/register/RegisterScreen'
export {default as ForgotPasswordScreen} from './Auth/forgotPassword/ForgotPasswordScreen'
export {default as ResetPasswordScreen} from './Auth/resetPassword/ResetPasswordScreen'
export {default as IndexPage} from './privatePages/indexPage/IndexPage'
export {default as HomePage} from './privatePages/home/HomePage'
export {default as Message} from './privatePages/message/Message'
