export {default as LoginScreen2} from './Auth/login/LoginScreen2'
export {default as RegisterScreen} from './Auth/register/RegisterScreen'
export {default as ForgotPasswordScreen} from './Auth/forgotPassword/ForgotPasswordScreen'
export {default as ResetPasswordScreen} from './Auth/resetPassword/ResetPasswordScreen'
export {default as IndexPage} from './privatePages/indexPage/IndexPage'
export {default as HomePage} from './privatePages/home/HomePage'
export {default as Message} from './privatePages/message/Message'
export {default as MessageDetails} from './privatePages/message/messageDetails/MessageDetails'
export {default as Discover} from './privatePages/discover/Discover'
export {default as Notify} from './privatePages/notify/Notify'
export {default as Profile} from './privatePages/profile/Profile'
export {default as PostDetails} from './privatePages/postDetails/PostDetails'
// porfolio pages

export {default as PorfolioHome} from './myPorfolioSite/home/Home'
