export {default as NotFound} from './notFound/NotFound'
export {default as Alert} from './alert/Alert'
export {default as Loading} from './loading/Loading'
export {default as Toast} from './toast/Toast'
export {default as Social2Header} from './headers/social2Header/Header'
export {default as MainHeader} from './headers/mainHeader/Header'
