export {default as NotFound} from './notFound/NotFound'
export {default as Alert} from './alert/Alert'
export {default as Loading} from './loading/Loading'
export {default as Toast} from './toast/Toast'
export {default as Social2Header} from './headers/social2Header/Header'
export {default as MainHeader} from './headers/mainHeader/Header'
export {default as Avatar} from './avatar/Avatar'
export {default as Menu} from './menu/Menu'
export {default as Search} from './search/Search'
export {default as UserCard} from './usercard/UserCard'
export {default as Info} from './info/Info'
export {default as Posts} from './posts/Posts'
export {default as ProfilePost} from './posts/profilePost/ProfilePost'
export {default as PorfilePostCard} from './posts/profilePost/porfilePostCard/PorfilePostCard'
export {default as PostCardHeader} from './posts/postCardHeader/PostCardHeader'
export {default as PostCardBody} from './posts/postCardBody/PostCardBody'
export {default as PostCardFooter} from './posts/postCardFooter/PostCardFooter'
export {default as PostThumb} from './posts/postThumb/PostThumb'
export {default as EditProfile} from './editprofile/EditProfile'
export {default as FollowBtn} from './buttons/followbtn/FollowBtn'
export {default as FollowBtn2} from './buttons/followbtn/FollowBtn2'
export {default as LikeButton} from './buttons/likeButton/LikeButton'
export {default as LoadMoreBtn} from './buttons/loadMoreBtn/LoadMoreBtn'
export {default as Followers} from './followers/Followers'
export {default as Following} from './following/Following'
export {default as Status} from './status/Status'
export {default as Avatar1} from './avatar/avatar1/Avatar1'
export {default as Avatar2}  from './avatar/avatar2/Avatar2'
export {default as StatusModal} from './status/statusModal/StatusModal'
export {default as Carousel} from './carousel/Carousel'
export {default as Comments} from './comments/Comments'
export {default as InputComments} from './comments/inputComments/InputComments'
export {default as CommentDisplay} from './comments/commentDisplay/CommentDisplay'
export {default as CommentCard} from './comments/commentCard/CommentCard'
export {default as CommentMenu} from './comments/commentMenu/CommentMenu'
export {default as ShareModal} from './share/ShareModal'
export {default as RightSideBar} from './rightSideBar/RightSideBar'
export {default as Saved} from './save/Saved'
export {default as NotifyModal} from './notify/notifyModal/NotifyModal'
export {default as MessageLeftSide} from './message/messageLeftside/MessageLeftSide'
export {default as MessageRightSide} from './message/messageRightSide/MessageRightSide'
export {default as MessageDisplay} from './message/messageDisplay/MessageDisplay'
export {default as Icons} from './icons/Icons'
export {default as CallModal} from './call/CallModal'
export {default as Times} from './times/Times'
export {default as SelectFamilyCard} from './family/selectFamilyCard/SelectFamilyCard'
export {default as DisplayCard} from './displayCard/DisplayCard'
export {default as Input} from './helperInput/Input'
export {default as Table} from './table/Table'
export {default as Pagination} from './pagination/Pagination'
//porfolio components exports starts
export {default as ProfileNavbar} from './portfolioComponents/navbar/ProfileNavbar'
export {default as ProfileHeader} from './portfolioComponents/header/ProfileHeader'
export {default as ProfileHome} from './portfolioComponents/home/ProfileHome'
export {default as ProfileAbout} from './portfolioComponents/about/PorfileAbout'
export {default as ProfileService} from './portfolioComponents/service/ProfileService'
export {default as ProfilePortfolio} from './portfolioComponents/portfolio/ProfilePortfolio'
export {default as Popup} from './portfolioComponents/popup/Popup'
export {default as PortfolioItem} from './portfolioComponents/portfolio/portfolioItem/PortfolioItems'
export {default as Testimonial} from './portfolioComponents/testimonial/Testimonial'
export {default as TestimonialItem} from './portfolioComponents/testimonial/testimonialItem/TestimonialItem'
export {default as Contact} from './portfolioComponents/contact/Contact'
export {default as Switcher} from './portfolioComponents/switcher/Switcher'
export {default as Preloader} from './portfolioComponents/preloader/Preloader'
//porfolio components exports end


//admin
export {default as AdminSchoolPreviewPopup} from './admin/adminSchoolPreviewPopup/AdminSchoolPreviewPopup'
export {default as AdminSchoolCards} from './admin/adminSchoolCard/AdminSchoolCards'
export {default as DepartmentInfoPopup} from './admin/application/departmentInfoPopup/DepartmentInfoPopup'
export {default as AdminUnclearPopup} from './admin/application/unclearPopup/UnclearPopup'
export {default as AdminResume}from './admin/resume/Resume'
export {default as AdminSturcturalPeoplePopUpDetail} from './admin/application/sturcturalPeoplePopUpDetail/SturcturalPeoplePopUpDetail'
export {default as AdminSources} from './admin/source/Source'
export {default as AdminApplicationProfileView} from './admin/application/ProfileView'
export {default as AdminApplicationProfileEdit} from './admin/application/ProfileEdit'
export {default as AdminApplicationCard} from './admin/application/Cards'
export {default as AdminApplicationStructure} from './admin/application/Structure'
export {default as AdminExpenseMain} from './admin/expense/AdminExpenseMain/AdminExpenseMain'
export {default as AdminExpenseDetails} from './admin/expense/AdminExpenseDetails/AdminExpenseDetails'
export {default as AdminToast} from './admin/toast/Toast'
export {default as DateHistogram} from './admin/dateHistogram/DateHistogram'
export {default as BubbleMap} from './admin/bubbleMap/BubbleMap'
export {default as Dropdown} from './admin/dropDown/Dropdown'
export {default as ColorLegend} from './admin/colorLegend/ColorLegend'
export {default as AdminSideBar} from './admin/adminSideBar/AdminSideBar'
export {default as DisplayCssColorsPie} from './admin/svg/DisplayCssColorsPie/DisplayCssColorsPie'
export {default as AdminRevenueCard} from './admin/revenueCard/RevenueCard'
export {default as AdminSalariesVSJobs} from './admin/salaryVSjobs/SalariesVSJobs'
export {default as DisplayCssColorsHis} from './admin/DisplayCssColorsHis/DisplayCssColorsHis'
export {default as AxisBottom} from './admin/DisplayCssColorsHis/AxisBottom'
export {default as AxisLeft} from './admin/DisplayCssColorsHis/AxisLeft'
export {default as Marks} from './admin/DisplayCssColorsHis/Marks'

export {default as IrishFlower} from './admin/IrishFlower/IrishFlower'
export {default as AxisBottomIrish} from './admin/IrishFlower/AxisBottom_irish'
export {default as AxisLeftIrish} from './admin/IrishFlower/AxisLeft_irish'
export {default as MarksIrish} from './admin/IrishFlower/Marks_irish'

export {default as GlobalTemp} from './admin/GlobalTemp/GlobalTemp'
export {default as AxisBottomTemp} from './admin/GlobalTemp/AxisBottom_temp'
export {default as AxisLeftTemp} from './admin/GlobalTemp/AxisLeft_temp'
export {default as MarksTemp} from './admin/GlobalTemp/Marks_temp'

export {default as WorldMap} from './admin/WorldMap/WorldMap'
export {default as AxisBottomMap} from './admin/WorldMap/AxisBottom_map'
export {default as AxisLeftMap} from './admin/WorldMap/AxisLeft_map'
export {default as MarksMap} from './admin/WorldMap/Marks_map'

export {default as Migrands} from './admin/Migrands/Migrands'
export {default as AxisBottomMig} from './admin/Migrands/AxisBottom_mig'
export {default as AxisLeftMig} from './admin/Migrands/AxisLeft_mig'
export {default as MarksMig} from './admin/Migrands/Marks_mig'


export {default as WorldMapMig} from './admin/MissingMigrandsWorldMap/WorldMap_mig'
export {default as AxisBottomMigMap} from './admin/MissingMigrandsWorldMap/AxisBottom_map_mig'
export {default as AxisLeftMigMap} from './admin/MissingMigrandsWorldMap/AxisLeft_map_mig'
export {default as MarksMigMap} from './admin/MissingMigrandsWorldMap/Marks_map_mig'
