export {default as NotFound} from './notFound/NotFound'
export {default as Alert} from './alert/Alert'
export {default as Loading} from './loading/Loading'
export {default as Toast} from './toast/Toast'
export {default as Social2Header} from './headers/social2Header/Header'
export {default as MainHeader} from './headers/mainHeader/Header'
export {default as Avatar} from './avatar/Avatar'
export {default as Menu} from './menu/Menu'
export {default as Search} from './search/Search'
export {default as UserCard} from './usercard/UserCard'
export {default as Info} from './info/Info'
export {default as Posts} from './posts/Posts'
export {default as EditProfile} from './editprofile/EditProfile'
export {default as FollowBtn} from './buttons/followbtn/FollowBtn'
//porfolio components exports starts
export {default as ProfileNavbar} from './portfolioComponents/navbar/ProfileNavbar'
export {default as ProfileHeader} from './portfolioComponents/header/ProfileHeader'
export {default as ProfileHome} from './portfolioComponents/home/ProfileHome'
export {default as ProfileAbout} from './portfolioComponents/about/PorfileAbout'
export {default as ProfileService} from './portfolioComponents/service/ProfileService'
export {default as ProfilePortfolio} from './portfolioComponents/portfolio/ProfilePortfolio'
export {default as Popup} from './portfolioComponents/popup/Popup'
export {default as PortfolioItem} from './portfolioComponents/portfolio/portfolioItem/PortfolioItems'
export {default as Testimonial} from './portfolioComponents/testimonial/Testimonial'
export {default as TestimonialItem} from './portfolioComponents/testimonial/testimonialItem/TestimonialItem'
export {default as Contact} from './portfolioComponents/contact/Contact'
export {default as Switcher} from './portfolioComponents/switcher/Switcher'
//porfolio components exports end
